{% set name = "leptonica" %}
{% set version = "1.82.0" %}
{% set sha256 = "155302ee914668c27b6fe3ca9ff2da63b245f6d62f3061c8f27563774b8ae2d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/DanBloomberg/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cmake.patch  # [win]

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    - xz

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf      # [not win]
    - automake      # [not win]
    - make          # [not win]
    - libtool       # [not win]
    - m4            # [not win]
    - pkg-config    # [not win]
    - cmake         # [win]
    - curl          # [win]
    - m2-unzip      # [win]
  host:
    # TODO: conda-forge giflib missing headers on windows?
    - giflib        # [not win]
    - jpeg
    - libpng
    - libtiff
    - libwebp
    - openjpeg
    - xz
    - zlib
  run:


test:
  commands:
    - convertfilestopdf --help 2>&1 | grep 'resolution' &> /dev/null  # [not win]

about:
  home: https://github.com/DanBloomberg/leptonica
  license: BSD-2-Clause
  license_family: BSD
  license_file: leptonica-license.txt
  license_url: https://github.com/DanBloomberg/leptonica/blob/master/leptonica-license.txt
  summary: Useful for image processing and image analysis applications
  description: |
    Leptonica is a pedagogically-oriented open source site containing	
    software that is broadly useful for image processing and image	
    analysis applications.
  # HTTPS isn't available for doc_url
  doc_url: http://www.leptonica.org/
  dev_url: https://github.com/DanBloomberg/leptonica

extra:
  recipe-maintainers:
    - CurtLH
    - izahn
