travis:
  secure:
    BINSTAR_TOKEN: HCX5tlkS5q9MWpB43yvg4Srsx2+qNBikDfXJh7YPPTTztUrNQs2QYKn61lYBx/YpnulioZMstp5rGGlrdf3znfl3NhHLZw24UUIWO24Y1euW3Plg+eoPHlfNt3YXkQoS3DJ55/pISh9NaUhB/ftMaGhq+oENqrvmn6t6gDUJVCti4+nztYcR+m9ZW+/15D9glOK01EhLyGaSRIJdr3h1t1Jwms/iINn4QtYXqt0m7xUxxMkAFQoONJQF1MnfbBAfpvbBVQ9ntUkcuXIdgEU7dXlqFjraDgjCFe85QnZFbuUoMsiiv/WhcOuEOXgwmS8eoO960JYp9OF2Z+muZqi3jeAT1X2El6OvoIFAzvKYCHK8/OpgAffzP9O72SPayyBM5qz67S3L1GFwpq2+VP412elVmA/MHxbtkpUKgMo8RsVeGFzDS4lwj+XFDJLhzlHiJa/qvL3PvM3T4z2cMrCO2uthUF9Biq4pcRjoWoUPKlb9FlsdvQ4PwZliD713WfiyJf6pCU8wwsv3cTI8Fs6gEZ+HB5Ba4qc0eQzOoYEbDjMF3JYYhw9X6XuaIddMjFgNS+VARIQk5GNaWnMDKUVASlUjjFLa94aRJca6oY0BIbU8ehLaiRPrlOiGIU8OTTvbUsrLpOb61tb00ElgfVviJu9toZq09lcKHR5CGcwJ+Lk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
